---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: nsm-workloads-webhook
spec:
  spiffeIDTemplate: "spiffe://{{.TrustDomain}}/ns/{{.PodMeta.Namespace}}/pod/{{.PodMeta.Name}}"
  dnsNameTemplates: ["{{index .PodMeta.Labels \"dns-name\"}}.{{.PodMeta.Namespace}}", "{{index .PodMeta.Labels \"dns-name\"}}.{{.PodMeta.Namespace}}.svc"]
  podSelector:
    matchLabels:
      spiffe.io/spiffe-id-webhook: "true"
